import {
    StyleSheet,
    Text,
    View,
    ScrollView,
    TouchableOpacity,
    Dimensions,
  } from 'react-native';
  import { LinearGradient } from 'expo-linear-gradient';
  import { colors } from '../constants/colors';
  
  const { width } = Dimensions.get('window');
  const isMobile = width <= 480;
  
  interface Props {
    onGetStarted: () => void;
  }
  
  export default function LandingScreen({ onGetStarted }: Props) {
    const features = [
      { emoji: '⛅', title: 'Weather Intelligence', desc: 'Real-time weather analysis tells you exactly when to go out.' },
      { emoji: '🧠', title: 'AI Decision Engine', desc: 'AI makes smart decisions without you asking anything.' },
      { emoji: '🔋', title: 'Energy Tracker', desc: 'Track your daily energy based on sleep and weather.' },
      { emoji: '🧬', title: 'Weather DNA', desc: 'AI learns your unique weather preferences over time.' },
      { emoji: '🥾', title: 'Hiking Guide', desc: 'Best trails recommended based on today\'s conditions.' },
      { emoji: '📅', title: 'Daily Planner', desc: 'Smart plans generated by AI every morning.' },
    ];
  
    return (
      <View style={styles.container}>
        <ScrollView showsVerticalScrollIndicator={false}>
  
          {/* NAV */}
          <LinearGradient
            colors={['#050d1a', '#050d1a']}
            style={styles.nav}
          >
            <Text style={styles.navLogo}>RYTHMIQ</Text>
            <TouchableOpacity style={styles.navBtn} onPress={onGetStarted}>
              <Text style={styles.navBtnText}>Get Started</Text>
            </TouchableOpacity>
          </LinearGradient>
  
          {/* HERO */}
          <LinearGradient
            colors={['#050d1a', '#0a1628', '#050d1a']}
            style={styles.hero}
          >
            {/* Badge */}
            <View style={styles.heroBadge}>
              <Text style={styles.heroBadgeText}>🧠 AI Powered Life Assistant</Text>
            </View>
  
            {/* Title */}
            <Text style={styles.heroTitle}>Live Life On Your</Text>
            <LinearGradient
              colors={['#2d8eff', '#00c6ff', '#00e676']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 0 }}
              style={styles.gradientTextBox}
            >
              <Text style={styles.heroTitleGradient}>Rhythm</Text>
            </LinearGradient>
  
            {/* Subtitle */}
            <Text style={styles.heroSubtitle}>
              Rythmiq analyzes your weather, sleep, and energy to proactively guide your day — no typing needed.
            </Text>
  
            {/* Feature Badges */}
            <View style={styles.badgesRow}>
              {['⛅ Weather', '🔋 Energy', '🧬 DNA', '🥾 Hiking', '📅 Planner', '🔔 Alerts'].map((badge, i) => (
                <View key={i} style={styles.badge}>
                  <Text style={styles.badgeText}>{badge}</Text>
                </View>
              ))}
            </View>
  
            {/* CTA Buttons */}
            <View style={styles.ctaRow}>
              <TouchableOpacity onPress={onGetStarted}>
                <LinearGradient
                  colors={['#2d8eff', '#00c6ff']}
                  style={styles.ctaPrimary}
                  start={{ x: 0, y: 0 }}
                  end={{ x: 1, y: 0 }}
                >
                  <Text style={styles.ctaPrimaryText}>🚀 Get Started</Text>
                </LinearGradient>
              </TouchableOpacity>
              <TouchableOpacity style={styles.ctaSecondary} onPress={onGetStarted}>
                <Text style={styles.ctaSecondaryText}>View Demo →</Text>
              </TouchableOpacity>
            </View>
  
          </LinearGradient>
  
          {/* STATS */}
          <LinearGradient
            colors={['#0d1f3c', '#050d1a']}
            style={styles.stats}
          >
            {[
              { value: '6', label: 'App Screens' },
              { value: '24/7', label: 'AI Monitoring' },
              { value: '100%', label: 'Personalized' },
              { value: '∞', label: 'Possibilities' },
            ].map((stat, index) => (
              <View key={index} style={styles.statItem}>
                <Text style={styles.statValue}>{stat.value}</Text>
                <Text style={styles.statLabel}>{stat.label}</Text>
              </View>
            ))}
          </LinearGradient>
  
          {/* FEATURES */}
          <View style={styles.features}>
            <Text style={styles.featuresTitle}>Everything You Need</Text>
            <Text style={styles.featuresSubtitle}>Powered by AI, designed for your life</Text>
            <View style={styles.featuresGrid}>
              {features.map((feature, index) => (
                <LinearGradient
                  key={index}
                  colors={['#0d1f3c', '#050d1a']}
                  style={styles.featureCard}
                >
                  <Text style={styles.featureEmoji}>{feature.emoji}</Text>
                  <Text style={styles.featureTitle}>{feature.title}</Text>
                  <Text style={styles.featureDesc}>{feature.desc}</Text>
                </LinearGradient>
              ))}
            </View>
          </View>
  
          {/* CTA BOTTOM */}
          <LinearGradient
            colors={['#0a1628', '#050d1a']}
            style={styles.ctaBottom}
          >
            <Text style={styles.ctaBottomTitle}>Ready to find your Rhythm?</Text>
            <Text style={styles.ctaBottomSubtitle}>
              Join thousands living smarter with Rythmiq
            </Text>
            <TouchableOpacity onPress={onGetStarted}>
              <LinearGradient
                colors={['#2d8eff', '#00c6ff']}
                style={styles.ctaBottomBtn}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 0 }}
              >
                <Text style={styles.ctaBottomBtnText}>🚀 Start Now — It's Free</Text>
              </LinearGradient>
            </TouchableOpacity>
          </LinearGradient>
  
          {/* FOOTER */}
          <View style={styles.footer}>
            <Text style={styles.footerText}>
              Built with ❤️ by Muhammad Midhat
            </Text>
            <Text style={styles.footerApp}>RYTHMIQ © 2026</Text>
          </View>
  
          <View style={{ height: 40 }} />
  
        </ScrollView>
      </View>
    );
  }
  
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#050d1a',
    },
    nav: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      paddingTop: 50,
      borderBottomWidth: 1,
      borderBottomColor: '#1a3a5c',
    },
    navLogo: {
      fontSize: 16,
      fontWeight: '800',
      color: '#2d8eff',
      letterSpacing: 4,
    },
    navBtn: {
      backgroundColor: 'rgba(45,142,255,0.15)',
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: 'rgba(45,142,255,0.3)',
    },
    navBtnText: {
      color: '#2d8eff',
      fontSize: 13,
      fontWeight: '600',
    },
    hero: {
      padding: 24,
      paddingTop: 40,
      alignItems: 'center',
    },
    heroBadge: {
      backgroundColor: 'rgba(45,142,255,0.15)',
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: 'rgba(45,142,255,0.3)',
      marginBottom: 24,
    },
    heroBadgeText: {
      color: '#2d8eff',
      fontSize: 13,
      fontWeight: '600',
    },
    heroTitle: {
      fontSize: 42,
      fontWeight: '800',
      color: '#ffffff',
      textAlign: 'center',
      lineHeight: 48,
    },
    gradientTextBox: {
      borderRadius: 8,
      marginBottom: 20,
    },
    heroTitleGradient: {
      fontSize: 42,
      fontWeight: '800',
      color: '#ffffff',
      textAlign: 'center',
      padding: 4,
    },
    heroSubtitle: {
      fontSize: 16,
      color: '#4a6e8a',
      textAlign: 'center',
      lineHeight: 26,
      marginBottom: 24,
      paddingHorizontal: 8,
    },
    badgesRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      justifyContent: 'center',
      marginBottom: 32,
    },
    badge: {
      backgroundColor: 'rgba(255,255,255,0.05)',
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.1)',
    },
    badgeText: {
      color: '#a8c0d6',
      fontSize: 13,
    },
    ctaRow: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'center',
    },
    ctaPrimary: {
      paddingHorizontal: 28,
      paddingVertical: 14,
      borderRadius: 30,
    },
    ctaPrimaryText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '700',
    },
    ctaSecondary: {
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: 'rgba(45,142,255,0.4)',
    },
    ctaSecondaryText: {
      color: '#2d8eff',
      fontSize: 16,
      fontWeight: '600',
    },
    stats: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      padding: 24,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: '#1a3a5c',
    },
    statItem: {
      alignItems: 'center',
    },
    statValue: {
      fontSize: 32,
      fontWeight: '800',
      color: '#2d8eff',
    },
    statLabel: {
      fontSize: 11,
      color: '#4a6e8a',
      marginTop: 4,
      textAlign: 'center',
    },
    features: {
      padding: 24,
    },
    featuresTitle: {
      fontSize: 28,
      fontWeight: '800',
      color: '#ffffff',
      textAlign: 'center',
      marginBottom: 8,
    },
    featuresSubtitle: {
      fontSize: 14,
      color: '#4a6e8a',
      textAlign: 'center',
      marginBottom: 24,
    },
    featuresGrid: {
      gap: 12,
    },
    featureCard: {
      borderRadius: 20,
      padding: 20,
      borderWidth: 1,
      borderColor: '#1a3a5c',
    },
    featureEmoji: {
      fontSize: 32,
      marginBottom: 10,
    },
    featureTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: '#ffffff',
      marginBottom: 6,
    },
    featureDesc: {
      fontSize: 13,
      color: '#4a6e8a',
      lineHeight: 20,
    },
    ctaBottom: {
      padding: 40,
      alignItems: 'center',
      borderTopWidth: 1,
      borderColor: '#1a3a5c',
    },
    ctaBottomTitle: {
      fontSize: 28,
      fontWeight: '800',
      color: '#ffffff',
      textAlign: 'center',
      marginBottom: 8,
    },
    ctaBottomSubtitle: {
      fontSize: 14,
      color: '#4a6e8a',
      textAlign: 'center',
      marginBottom: 24,
    },
    ctaBottomBtn: {
      paddingHorizontal: 32,
      paddingVertical: 16,
      borderRadius: 30,
    },
    ctaBottomBtnText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '700',
    },
    footer: {
      padding: 24,
      alignItems: 'center',
      borderTopWidth: 1,
      borderColor: '#1a3a5c',
    },
    footerText: {
      fontSize: 13,
      color: '#4a6e8a',
      marginBottom: 4,
    },
    footerApp: {
      fontSize: 13,
      color: '#2d8eff',
      fontWeight: '700',
      letterSpacing: 2,
    },
  });